name: Build Android APK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5' # 使用项目所需的Flutter版本
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Check Flutter doctor
      run: flutter doctor

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: dart_simple_live_apk
        path: build/app/outputs/flutter-apk/app-release.apk
